# Generated by Django 4.2.5 on 2023-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_order_alter_book_created_at_book_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
